@startuml

Title Solution architecture

queue "Kafka" as K
interface "Payment API" as PA
database "Database" as DB
rectangle "Payment dispatcher" <<online>> as PDON
rectangle "Payment dispatcher" <<offline>> as PDOFF
rectangle "Payment checker" as PC
rectangle "Payment updater" as PU

K <- PDOFF: consume
PDOFF -> PU: update
PU -> DB: update
K <-u- PDON: consume
PDON -> PC: update
PC -> PA: check
PC --> PU: update

@enduml
