@startuml

Title Offline payment flow

queue "Kafka" as K
participant "Payment dispatcher" as PD
participant "Payment updater" as PU
database "Database" as DB

PD -> K: consume
activate PD
activate K
K --> PD: mesasge
deactivate K
PD -> PU: process
activate PU
PU -> DB: update payment
activate DB
DB --> PU: update ok
deactivate DB
PU --> PD: update ok
deactivate PU
PD -> K: commit
activate K
K --> PD
deactivate K
deactivate PD

@enduml
