@startuml

Title Online payment flow

queue "Kafka" as K
participant "Payment dispatcher" as PD <<online>>
participant "Payment checker" as PP
participant "Payment updater" as PU
participant "Payment API" as PA
database "Database" as DB

PD -> K: consume
activate PD
activate K
K --> PD: mesasge
deactivate K
PD -> PP: update
activate PP
PP -> PA: check payment
activate PA
PA --> PP: check ok
deactivate PA
PP -> PU: update payment
activate PU
PU -> DB: persist payment
activate DB
DB --> PU: ok
deactivate DB
PU --> PP: update ok
deactivate PU
PP --> PD: update ok
deactivate PP
PD -> K: commit
activate K
K --> PD
deactivate K
deactivate PD

@enduml
